#!/usr/bin/env python3
"""Generates the inputs for the headless gameplay harness.

  python3 tests/harness/build.py [path/to/globalTypes.d.luau]

* generated/Sources.luau     every module under src/ as a string, keyed by path
* generated/ApiMembers.luau  property/method names per Roblox class, extracted
                             from luau-lsp's Roblox definitions file, so the mock
                             rejects invalid members exactly like the engine.
                             Only regenerated when a definitions path is given.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(HERE, "generated")

CLASSES = [
    "Instance", "PVInstance", "BasePart", "FormFactorPart", "Part", "WedgePart", "SpawnLocation",
    "Model", "Folder", "Humanoid", "HumanoidDescription", "Player", "Attachment", "Trail",
    "Weld", "JointInstance", "WeldConstraint", "SpecialMesh", "FileMesh", "DataModelMesh",
    "Smoke", "Fire", "Sparkles", "ParticleEmitter", "PointLight", "Light",
    "SurfaceGui", "SurfaceGuiBase", "LayerCollector", "GuiBase2d", "BillboardGui",
    "TextLabel", "GuiLabel", "GuiObject", "ProximityPrompt", "RemoteEvent", "BaseRemoteEvent",
    "BindableEvent", "IntValue", "ValueBase", "Sound", "Lighting", "Workspace", "WorldRoot",
    "Model", "Players", "CFrameValue", "Decal", "FaceInstance", "Accessory", "Accoutrement",
    "Shirt", "Pants", "Clothing", "ShirtGraphic", "BodyColors", "Script", "ModuleScript",
    "LuaSourceContainer", "BaseScript", "ServiceProvider", "DataModel",
    "GuiBase", "GuiBase2d", "CharacterAppearance", "Object",
    # client UI
    "ScreenGui", "Frame", "TextButton", "GuiButton", "ScrollingFrame", "UIListLayout",
    "UIGridLayout", "UIGridStyleLayout", "UILayout", "UIComponent", "UIBase", "UICorner",
    "UIStroke", "UIPadding", "UIScale", "UIGradient", "Camera", "PlayerGui", "BasePlayerGui",
    "PlayerScripts", "LocalScript", "LinearVelocity", "Constraint",
    "Atmosphere", "PostEffect", "BloomEffect", "ColorCorrectionEffect", "SunRaysEffect",
]


def lua_string(text: str) -> str:
    level = 1
    while ("]" + "=" * level + "]") in text:
        level += 1
    eq = "=" * level
    return f"[{eq}[\n{text}]{eq}]"


def build_sources():
    lines = ["-- generated by build.py: do not edit", "return {"]
    src = os.path.join(ROOT, "src")
    for dirpath, _, files in os.walk(src):
        for name in sorted(files):
            if not name.endswith(".luau"):
                continue
            full = os.path.join(dirpath, name)
            key = os.path.relpath(full, src).replace(os.sep, "/")
            with open(full, encoding="utf-8") as fh:
                lines.append(f"\t[{key!r}] = {lua_string(fh.read())},")
    lines.append("}")
    with open(os.path.join(OUT, "Sources.luau"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def build_members(defs_path: str):
    classes, parents, cur = {}, {}, None
    with open(defs_path, encoding="utf-8") as fh:
        for line in fh:
            m = re.match(r"declare (?:extern type|class) (\w+)(?: extends (\w+))?", line)
            if m:
                cur = m.group(1)
                parents[cur] = m.group(2)
                classes.setdefault(cur, set())
                if line.rstrip().endswith("end"):
                    cur = None
                continue
            if line.startswith("end"):
                cur = None
                continue
            if cur:
                m = re.match(r"\s+(?:read |write )?(\w+)\s*:", line) or re.match(r"\s+function (\w+)", line)
                if m:
                    classes[cur].add(m.group(1))
    out = ["-- generated by build.py from luau-lsp's Roblox definitions: do not edit", "return {"]
    for cls in sorted(set(CLASSES)):
        if cls not in classes:
            continue
        members = ", ".join(f'"{m}"' for m in sorted(classes[cls]))
        out.append(f"\t{cls} = {{ Parent = {parents.get(cls) and repr(parents[cls]).replace(chr(39), chr(34)) or 'nil'}, Members = {{ {members} }} }},")
    out.append("}")
    with open(os.path.join(OUT, "ApiMembers.luau"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    build_sources()
    if len(sys.argv) > 1:
        build_members(sys.argv[1])
    print("harness inputs generated in", OUT)
